### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Miki34534** [The404Hacking/websploit#1]
$ python2 websploit.py
Traceback (most recent call last):
  File "websploit.py", line 55, in <module>
    from modules import arp_poisoner
  File "/data/data/com.termux/files/home/websploit/Setup/websploit/websploit/modules/arp_poisoner.py", line 11, in <module>
    from scapy.all import *
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/scapy/all.py", line 27, in <module>
    from scapy.route import *
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/scapy/route.py", line 203, in <module>
    conf.iface = get_working_if()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/scapy/arch/linux.py", line 144, in get_working_if
    for i in get_if_list():
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/scapy/arch/linux.py", line 127, in get_if_list
    f.close()
Unbou

**Comment by Syntax0001** [comment]
У меня такая же херня: (

**Comment by krishpranav** [comment]
delete websploit and re clone it

**Comment by krishpranav** [comment]
scapy is not imported

**Comment by Neteller37** [comment]
> delete websploit and re clone it 

Not working
