### ISSUE TITLE
Not able to import scapy.all

### ISSUE THREAD

**Issue by B1tBr34k3r** [The404Hacking/websploit#5]
Traceback (most recent call last):
  File "websploit.py", line 55, in <module>
    from modules import arp_poisoner
  File "/home/prakhar/Desktop/websploit/modules/arp_poisoner.py", line 11, in <module>
    from scapy.all import *
ImportError: No module named scapy.all

**Comment by radeongear** [comment]
pip2 install scapy

**Comment by sadesguy** [comment]
```

cd  /usr/lib/python3/dist-packages/

 cp -R scapy /usr/lib/python2.7/dist-packages/

```
